# Generated by Django 5.0.3 on 2024-03-19 07:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[('skill_category', 'skill_category'), ('skill_sub_category', 'skill_sub_category'), ('skill', 'skill')], max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.choicelist')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('preferred_employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelancer', 'Freelancer'), ('Contract', 'Contract')], max_length=30)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('other', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.choicelist')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.people')),
            ],
        ),
        migrations.AddIndex(
            model_name='choicelist',
            index=models.Index(fields=['name', 'choice_type'], name='api_choicel_name_c52eca_idx'),
        ),
        migrations.AddConstraint(
            model_name='choicelist',
            constraint=models.UniqueConstraint(fields=('name', 'choice_type'), name='name_choice_type_unique'),
        ),
    ]
